/**
* @File Name : newQuickAddPanel.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : June 12, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | June 12, 2025 |   | Initial Version
**/

public class newQuickAddPanel {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}